#! /usr/bin/python3

from PySide2.QtWidgets import QApplication
from PySide2.QtCore import QUrl,QCoreApplication,Qt
from PySide2.QtGui import QIcon
from PySide2.QtQml import QQmlApplicationEngine

import os
import sys
import LliurexOnedrive


QCoreApplication.setAttribute(Qt.AA_ShareOpenGLContexts)
app=QApplication()
engine=QQmlApplicationEngine()
engine.clearComponentCache()
context=engine.rootContext()
onedriveBridge=LliurexOnedrive.Bridge()
context.setContextProperty("onedriveBridge", onedriveBridge)

url = QUrl("/usr/share/lliurex-onedrive/rsrc/lliurex-onedrive.qml")


engine.load(url)
if not engine.rootObjects():
	sys.exit(-1)

engine.quit.connect(QApplication.quit)
app.setWindowIcon(QIcon("/usr/share/icons/hicolor/scalable/apps/lliurex-onedrive.svg"));
ret=app.exec_()
del engine
del app
sys.exit(ret)








'''	
#class Tunnel	
QCoreApplication.setAttribute(Qt.AA_ShareOpenGLContexts)
app = QApplication([])
tunnel = Tunnel()
view = QQuickView()
view.rootContext().setContextProperty("tunnel", tunnel)
url = QUrl("/home/lliurex/Escriptori/test2.qml")
view.setSource(url)
view.show()

sys.exit(app.exec_())
'''